import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const sampleReviews = [
  {
    customerName: 'Айгерим Б.',
    productName: 'Смартфон Samsung Galaxy',
    starRating: 5,
    reviewText: 'Тауар өте жақсы келді, қаптамасы таза, жеткізу жылдам. Рахмет! Өнімнің сапасы өте жоғары деңгейде.',
    category: 'quality',
    aiSentiment: 'positive',
    aiSentimentScore: 92,
    aiCategory: 'quality',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['жақсы келді', 'таза қаптама', 'жылдам жеткізу', 'жоғары сапа'],
    aiComplaintSummary: null,
    aiEmotion: 'joy',
  },
  {
    customerName: 'Марат С.',
    productName: 'Ноутбук Lenovo',
    starRating: 1,
    reviewText: 'Сломанный товар пришёл, упаковка порвана. Очень недоволен качеством доставки. Требую возврат денег немедленно!',
    category: 'delivery',
    aiSentiment: 'negative',
    aiSentimentScore: 8,
    aiCategory: 'packaging',
    aiCustomerClass: 'problematic',
    aiKeyPhrases: ['сломанный товар', 'упаковка порвана', 'недоволен', 'возврат денег'],
    aiComplaintSummary: 'Товар пришёл повреждённым с порванной упаковкой, клиент требует возврат.',
    aiEmotion: 'anger',
  },
  {
    customerName: 'Дина К.',
    productName: 'Кофемашина Philips',
    starRating: 3,
    reviewText: 'Нормально, ничего особенного. Доставка чуть задержалась на 2 дня. Товар соответствует описанию.',
    category: 'delivery',
    aiSentiment: 'neutral',
    aiSentimentScore: 50,
    aiCategory: 'delivery',
    aiCustomerClass: 'neutral',
    aiKeyPhrases: ['нормально', 'задержалась доставка', 'соответствует описанию'],
    aiComplaintSummary: null,
    aiEmotion: 'neutral',
  },
  {
    customerName: 'Нұрлан А.',
    productName: 'Спорттық аяқ киім Nike',
    starRating: 5,
    reviewText: 'Керемет! Аяқ киім өте сапалы, өлшемі дәл келді. Жеткізу 1 күнде болды. Тағы сатып аламын!',
    category: 'quality',
    aiSentiment: 'positive',
    aiSentimentScore: 96,
    aiCategory: 'quality',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['керемет', 'сапалы аяқ киім', 'дәл өлшем', '1 күнде жеткізу'],
    aiComplaintSummary: null,
    aiEmotion: 'joy',
  },
  {
    customerName: 'Светлана П.',
    productName: 'Платье летнее',
    starRating: 2,
    reviewText: 'Цвет не соответствует фото на сайте. Качество ткани ужасное, швы расходятся. Очень разочарована покупкой.',
    category: 'quality',
    aiSentiment: 'negative',
    aiSentimentScore: 15,
    aiCategory: 'quality',
    aiCustomerClass: 'problematic',
    aiKeyPhrases: ['цвет не соответствует', 'качество ужасное', 'швы расходятся', 'разочарована'],
    aiComplaintSummary: 'Товар не соответствует фото, плохое качество материала и пошива.',
    aiEmotion: 'disappointment',
  },
  {
    customerName: 'Бауыржан М.',
    productName: 'Планшет iPad',
    starRating: 4,
    reviewText: 'Өнім жақсы, бірақ бағасы біраз қымбат. Жеткізу уақытылы болды. Жалпы алғанда қанағаттанамын.',
    category: 'price',
    aiSentiment: 'positive',
    aiSentimentScore: 75,
    aiCategory: 'price',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['жақсы өнім', 'қымбат баға', 'уақытылы жеткізу', 'қанағаттанамын'],
    aiComplaintSummary: null,
    aiEmotion: 'satisfaction',
  },
  {
    customerName: 'Алексей В.',
    productName: 'Телевизор LG',
    starRating: 1,
    reviewText: 'Ужасный сервис! Телевизор привезли с царапинами. Служба поддержки не отвечает уже неделю. Никому не рекомендую!',
    category: 'service',
    aiSentiment: 'negative',
    aiSentimentScore: 5,
    aiCategory: 'service',
    aiCustomerClass: 'problematic',
    aiKeyPhrases: ['ужасный сервис', 'царапины', 'поддержка не отвечает', 'не рекомендую'],
    aiComplaintSummary: 'Доставили повреждённый товар, служба поддержки игнорирует клиента.',
    aiEmotion: 'anger',
  },
  {
    customerName: 'Зарина Т.',
    productName: 'Косметика L\'Oreal',
    starRating: 5,
    reviewText: 'Сапасы өте жоғары! Қаптамасы сыпайы және берік. Иісі тамаша. Бұл бренді барлығына ұсынамын!',
    category: 'packaging',
    aiSentiment: 'positive',
    aiSentimentScore: 94,
    aiCategory: 'packaging',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['жоғары сапа', 'сыпайы қаптама', 'тамаша иіс', 'ұсынамын'],
    aiComplaintSummary: null,
    aiEmotion: 'joy',
  },
  {
    customerName: 'Дмитрий К.',
    productName: 'Кроссовки Adidas',
    starRating: 3,
    reviewText: 'Товар нормальный, но доставка заняла 7 дней вместо обещанных 3. Упаковка помятая. В целом приемлемо.',
    category: 'delivery',
    aiSentiment: 'neutral',
    aiSentimentScore: 45,
    aiCategory: 'delivery',
    aiCustomerClass: 'neutral',
    aiKeyPhrases: ['нормальный товар', 'долгая доставка', 'помятая упаковка', 'приемлемо'],
    aiComplaintSummary: null,
    aiEmotion: 'disappointment',
  },
  {
    customerName: 'Гүлнар С.',
    productName: 'Сумка Michael Kors',
    starRating: 4,
    reviewText: 'Сумка өте әдемі, сапасы жақсы. Жеткізу жылдам болды. Тек бағасы қымбатырақ, бірақ сапасына лайық.',
    category: 'quality',
    aiSentiment: 'positive',
    aiSentimentScore: 80,
    aiCategory: 'quality',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['әдемі сумка', 'жақсы сапа', 'жылдам жеткізу', 'бағасына лайық'],
    aiComplaintSummary: null,
    aiEmotion: 'satisfaction',
  },
  {
    customerName: 'Иван Р.',
    productName: 'Холодильник Bosch',
    starRating: 2,
    reviewText: 'Холодильник шумит сильно ночью. Спать невозможно. Гарантийный мастер пришёл, но проблему не решил.',
    category: 'service',
    aiSentiment: 'negative',
    aiSentimentScore: 20,
    aiCategory: 'service',
    aiCustomerClass: 'problematic',
    aiKeyPhrases: ['шумит ночью', 'спать невозможно', 'проблема не решена', 'гарантийный мастер'],
    aiComplaintSummary: 'Холодильник издаёт громкий шум, гарантийный ремонт не помог.',
    aiEmotion: 'disappointment',
  },
  {
    customerName: 'Мадина Ж.',
    productName: 'Кітап "Алмас қылыш"',
    starRating: 5,
    reviewText: 'Кітап тез жетті, қаптамасы мықты болды. Кітаптың сапасы тамаша - қағаздары таза, баспасы анық.',
    category: 'packaging',
    aiSentiment: 'positive',
    aiSentimentScore: 90,
    aiCategory: 'packaging',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['тез жеткізу', 'мықты қаптама', 'тамаша сапа', 'анық баспа'],
    aiComplaintSummary: null,
    aiEmotion: 'joy',
  },
  {
    customerName: 'Олег С.',
    productName: 'Стиральная машина Samsung',
    starRating: 4,
    reviewText: 'Машина работает хорошо, тихая. Доставка и установка прошли без проблем. Цена немного высокая, но качество того стоит.',
    category: 'service',
    aiSentiment: 'positive',
    aiSentimentScore: 78,
    aiCategory: 'service',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['хорошо работает', 'тихая машина', 'доставка без проблем', 'высокая цена'],
    aiComplaintSummary: null,
    aiEmotion: 'satisfaction',
  },
  {
    customerName: 'Асем Н.',
    productName: 'Балалар ойыншықтары',
    starRating: 3,
    reviewText: 'Ойыншықтар жарамды, бірақ сипаттамасы мен нақты тауар арасында айырмашылық бар. Баласым ойнайды.',
    category: 'quality',
    aiSentiment: 'neutral',
    aiSentimentScore: 55,
    aiCategory: 'quality',
    aiCustomerClass: 'neutral',
    aiKeyPhrases: ['жарамды ойыншық', 'сипаттама сәйкес емес', 'бала ойнайды'],
    aiComplaintSummary: null,
    aiEmotion: 'neutral',
  },
  {
    customerName: 'Татьяна М.',
    productName: 'Духи Chanel',
    starRating: 1,
    reviewText: 'Подозреваю подделку! Запах совсем не тот, что у оригинала. Упаковка дешёвая, флакон кривой. Мошенники!',
    category: 'quality',
    aiSentiment: 'negative',
    aiSentimentScore: 3,
    aiCategory: 'quality',
    aiCustomerClass: 'problematic',
    aiKeyPhrases: ['подозрение в подделке', 'не тот запах', 'дешёвая упаковка', 'мошенники'],
    aiComplaintSummary: 'Клиент подозревает продажу поддельного товара, несоответствие оригиналу.',
    aiEmotion: 'anger',
  },
  {
    customerName: 'Ербол Қ.',
    productName: 'Велосипед Trek',
    starRating: 5,
    reviewText: 'Велосипед тамаша! Сапасы өте жоғары, жинақтау нұсқаулығы нақты. Жеткізу де тез болды. Өте риза!',
    category: 'quality',
    aiSentiment: 'positive',
    aiSentimentScore: 95,
    aiCategory: 'quality',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['тамаша велосипед', 'жоғары сапа', 'нақты нұсқаулық', 'тез жеткізу'],
    aiComplaintSummary: null,
    aiEmotion: 'joy',
  },
  {
    customerName: 'Надежда В.',
    productName: 'Постельное бельё',
    starRating: 2,
    reviewText: 'Цвет выгорел после первой стирки. Качество ткани очень плохое. За такие деньги ожидала большего.',
    category: 'quality',
    aiSentiment: 'negative',
    aiSentimentScore: 18,
    aiCategory: 'quality',
    aiCustomerClass: 'problematic',
    aiKeyPhrases: ['цвет выгорел', 'плохая ткань', 'не соответствует цене', 'разочарование'],
    aiComplaintSummary: 'Постельное бельё потеряло цвет после первой стирки, некачественная ткань.',
    aiEmotion: 'disappointment',
  },
  {
    customerName: 'Серік Б.',
    productName: 'Электр шайнек Tefal',
    starRating: 4,
    reviewText: 'Шайнек жақсы жұмыс істейді, тез қайнатады. Тек сыртқы дизайны қарапайым. Бағасы қолайлы.',
    category: 'price',
    aiSentiment: 'positive',
    aiSentimentScore: 72,
    aiCategory: 'price',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['жақсы жұмыс', 'тез қайнату', 'қарапайым дизайн', 'қолайлы баға'],
    aiComplaintSummary: null,
    aiEmotion: 'satisfaction',
  },
  {
    customerName: 'Александра Н.',
    productName: 'Кофе Lavazza',
    starRating: 5,
    reviewText: 'Кофе великолепный! Аромат потрясающий, вкус насыщенный. Упаковка герметичная, всё свежее. Заказываю уже третий раз!',
    category: 'packaging',
    aiSentiment: 'positive',
    aiSentimentScore: 97,
    aiCategory: 'packaging',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['великолепный кофе', 'потрясающий аромат', 'герметичная упаковка', 'заказываю третий раз'],
    aiComplaintSummary: null,
    aiEmotion: 'joy',
  },
  {
    customerName: 'Қанат Д.',
    productName: 'Теледидар Sony',
    starRating: 3,
    reviewText: 'Теледидар жұмыс істейді, суреті анық. Бірақ дыбысы күшті емес. Жеткізу кешіктірілді. Орташа баға.',
    category: 'delivery',
    aiSentiment: 'neutral',
    aiSentimentScore: 52,
    aiCategory: 'delivery',
    aiCustomerClass: 'neutral',
    aiKeyPhrases: ['жұмыс істейді', 'анық сурет', 'нашар дыбыс', 'кешіккен жеткізу'],
    aiComplaintSummary: null,
    aiEmotion: 'neutral',
  },
  {
    customerName: 'Михаил О.',
    productName: 'Кресло офисное',
    starRating: 1,
    reviewText: 'Кресло развалилось через месяц! Пластик хрупкий, ножки шатаются. Деньги выброшены на ветер. Ужас!',
    category: 'quality',
    aiSentiment: 'negative',
    aiSentimentScore: 7,
    aiCategory: 'quality',
    aiCustomerClass: 'problematic',
    aiKeyPhrases: ['развалилось', 'хрупкий пластик', 'ножки шатаются', 'деньги выброшены'],
    aiComplaintSummary: 'Кресло сломалось через месяц из-за некачественных материалов.',
    aiEmotion: 'anger',
  },
  {
    customerName: 'Айжан Р.',
    productName: 'Дәрі-дәрмек витаминдер',
    starRating: 5,
    reviewText: 'Витаминдер тез жетті, қаптамасы мықты. Сертификаттары бар, сапасына сенімдімін. Тағы заказ беремін!',
    category: 'packaging',
    aiSentiment: 'positive',
    aiSentimentScore: 88,
    aiCategory: 'packaging',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['тез жеткізу', 'мықты қаптама', 'сертификат бар', 'тағы заказ'],
    aiComplaintSummary: null,
    aiEmotion: 'satisfaction',
  },
  {
    customerName: 'Роман К.',
    productName: 'Наушники Sony WH-1000',
    starRating: 4,
    reviewText: 'Наушники отличные, звук чистый. Доставка быстрая. Немного дорого, но оно того стоит. Рекомендую!',
    category: 'price',
    aiSentiment: 'positive',
    aiSentimentScore: 82,
    aiCategory: 'price',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['отличные наушники', 'чистый звук', 'быстрая доставка', 'немного дорого'],
    aiComplaintSummary: null,
    aiEmotion: 'satisfaction',
  },
  {
    customerName: 'Балжан С.',
    productName: 'Тоңазытқыш LG',
    starRating: 2,
    reviewText: 'Тоңазытқыш 3 айдан кейін бұзылды. Кепілдік бойынша шеберлер келмейді. Ақшамды қайтарыңыздар!',
    category: 'service',
    aiSentiment: 'negative',
    aiSentimentScore: 12,
    aiCategory: 'service',
    aiCustomerClass: 'problematic',
    aiKeyPhrases: ['3 айда бұзылды', 'шеберлер келмейді', 'кепілдік жоқ', 'ақша қайтару'],
    aiComplaintSummary: 'Тоңазытқыш 3 айда бұзылды, кепілдік шеберлері келуден бас тартты.',
    aiEmotion: 'anger',
  },
  {
    customerName: 'Анатолий Г.',
    productName: 'Книга по программированию',
    starRating: 5,
    reviewText: 'Книга в отличном состоянии, доставка быстрая. Содержание очень полезное. Упаковали аккуратно в плёнку.',
    category: 'packaging',
    aiSentiment: 'positive',
    aiSentimentScore: 91,
    aiCategory: 'packaging',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['отличное состояние', 'быстрая доставка', 'полезное содержание', 'аккуратная упаковка'],
    aiComplaintSummary: null,
    aiEmotion: 'joy',
  },
  {
    customerName: 'Дильназ А.',
    productName: 'Гитара Yamaha',
    starRating: 3,
    reviewText: 'Гитара нормальная, бірақ баптауы дұрыс емес келді. Дүкеннен реттеп алдым. Жеткізу кешікті.',
    category: 'delivery',
    aiSentiment: 'neutral',
    aiSentimentScore: 48,
    aiCategory: 'delivery',
    aiCustomerClass: 'neutral',
    aiKeyPhrases: ['нормальная гитара', 'баптауы дұрыс емес', 'дүкеннен реттеу', 'кешіккен жеткізу'],
    aiComplaintSummary: null,
    aiEmotion: 'neutral',
  },
  {
    customerName: 'Сергей Л.',
    productName: 'Пылесос Dyson',
    starRating: 5,
    reviewText: 'Пылесос работает превосходно! Мощный, тихий, лёгкий. Доставили в день заказа. Упаковка идеальная.',
    category: 'quality',
    aiSentiment: 'positive',
    aiSentimentScore: 98,
    aiCategory: 'quality',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['превосходная работа', 'мощный и тихий', 'доставка в день заказа', 'идеальная упаковка'],
    aiComplaintSummary: null,
    aiEmotion: 'joy',
  },
  {
    customerName: 'Назерке Ж.',
    productName: 'Аяқ киім Baldinini',
    starRating: 2,
    reviewText: 'Аяқ киім өлшемі сәйкес емес келді. Қайтарғым келеді, бірақ қызмет нашар жауап береді. Өкінемін.',
    category: 'service',
    aiSentiment: 'negative',
    aiSentimentScore: 22,
    aiCategory: 'service',
    aiCustomerClass: 'problematic',
    aiKeyPhrases: ['өлшем сәйкес емес', 'қайтару қиын', 'нашар қызмет', 'өкіну'],
    aiComplaintSummary: 'Аяқ киім өлшемі дұрыс емес, қайтару кезінде қызмет нашар жұмыс істейді.',
    aiEmotion: 'disappointment',
  },
  {
    customerName: 'Константин Р.',
    productName: 'Фотоаппарат Canon',
    starRating: 4,
    reviewText: 'Фотоаппарат отличный, снимки чёткие. Комплектация полная. Цена немного завышена, но качество на уровне.',
    category: 'price',
    aiSentiment: 'positive',
    aiSentimentScore: 77,
    aiCategory: 'price',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['отличный фотоаппарат', 'чёткие снимки', 'полная комплектация', 'завышена цена'],
    aiComplaintSummary: null,
    aiEmotion: 'satisfaction',
  },
  {
    customerName: 'Ұлдана М.',
    productName: 'Планшеттік қалта',
    starRating: 4,
    reviewText: 'Қалта сапалы материалдан жасалған. Дизайны ұнады. Баға да қолайлы. Жеткізу 2 күнде болды.',
    category: 'quality',
    aiSentiment: 'positive',
    aiSentimentScore: 79,
    aiCategory: 'quality',
    aiCustomerClass: 'loyal',
    aiKeyPhrases: ['сапалы материал', 'ұнаған дизайн', 'қолайлы баға', '2 күнде жеткізу'],
    aiComplaintSummary: null,
    aiEmotion: 'satisfaction',
  },
];

async function main() {
  console.log('Seeding database...');

  // Create manager account
  const passwordHash = await bcrypt.hash('password123', 10);
  await prisma.manager.upsert({
    where: { email: 'manager@satisfai.kz' },
    update: {},
    create: {
      email: 'manager@satisfai.kz',
      passwordHash,
      name: 'Менеджер / Менеджер',
    },
  });
  console.log('Manager account created: manager@satisfai.kz / password123');

  // Clear existing reviews
  await prisma.review.deleteMany();

  // Create sample reviews with varying dates over the last 8 weeks
  const now = new Date();
  for (let i = 0; i < sampleReviews.length; i++) {
    const review = sampleReviews[i];
    const daysAgo = Math.floor(Math.random() * 56); // 0-56 days ago (8 weeks)
    const createdAt = new Date(now.getTime() - daysAgo * 24 * 60 * 60 * 1000);
    const analyzedAt = new Date(createdAt.getTime() + 5000);

    await prisma.review.create({
      data: {
        customerName: review.customerName,
        productName: review.productName,
        starRating: review.starRating,
        reviewText: review.reviewText,
        category: review.category,
        createdAt,
        aiSentiment: review.aiSentiment,
        aiSentimentScore: review.aiSentimentScore,
        aiCategory: review.aiCategory,
        aiCustomerClass: review.aiCustomerClass,
        aiKeyPhrases: review.aiKeyPhrases,
        aiComplaintSummary: review.aiComplaintSummary,
        aiEmotion: review.aiEmotion,
        aiAnalyzedAt: analyzedAt,
      },
    });
  }

  console.log(`${sampleReviews.length} sample reviews created.`);
  console.log('Seeding complete!');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
